# Generated by Django 3.0.1 on 2019-12-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urmart', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['product_id'], name='urmart_orde_product_ed4ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop_id'], name='urmart_prod_shop_id_092b80_idx'),
        ),
    ]
