version: '3.7'
services:
  database:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: urmart
      MYSQL_DATABASE: urmart
      MYSQL_USER: urmart
      MYSQL_PASSWORD: urmart
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_USER=urmart
      - PMA_PASSWORD=urmart
    restart: always
    ports:
      - 8080:80
volumes:
  db-data:
